package com.ss.siase.modelos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador", catalog = "sql9353038")
public class Administrador implements java.io.Serializable {

	public interface VistaPerfil {}
	
	@JsonView(VistaPerfil.class) private Integer idAdministrador;
	@JsonView(VistaPerfil.class) private Estatus estatus;
	@JsonView(VistaPerfil.class) private String nombre;
	@JsonView(VistaPerfil.class) private String usuario;
	private String contrasena;

	public Administrador() {
	}

	public Administrador(Estatus estatus, String nombre, String usuario) {
		this.estatus = estatus;
		this.nombre = nombre;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAdministrador", unique = true, nullable = false)
	public Integer getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(Integer idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstatus", nullable = false)
	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	
	@Column(name = "contrasena", nullable = false, length = 125)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
