package com.ss.siase.modelos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.ss.siase.modelos.Administrador.VistaPerfil;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "sql9353038")
public class Alumno implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@JsonView(VistaPerfil.class) private Integer idAlumno;
	@JsonView(VistaPerfil.class) private Estatus estatus;
	@JsonView(VistaPerfil.class) private String nombre;
	@JsonView(VistaPerfil.class) private String usuario;
	private String contrasena;
	@JsonView(VistaPerfil.class) private int matricula;

	public Alumno() {
	}

	public Alumno(Estatus estatus, String nombre, String usuario, String contrasena, int matricula) {
		this.estatus = estatus;
		this.nombre = nombre;
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.matricula = matricula;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAlumno", unique = true, nullable = false)
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstatus", nullable = false)
	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "contrasena", nullable = false, length = 125)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "matricula", nullable = false)
	public int getMatricula() {
		return this.matricula;
	}

	public void setMatricula(int matricula) {
		this.matricula = matricula;
	}

}
