package com.ss.siase.modelos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.ss.siase.modelos.Administrador.VistaPerfil;

/**
 * Maestro generated by hbm2java
 */
@Entity
@Table(name = "maestro", catalog = "sql9353038")
public class Maestro implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@JsonView(VistaPerfil.class) private Integer idMaestro;
	@JsonView(VistaPerfil.class) private Estatus estatus;
	@JsonView(VistaPerfil.class) private String nombre;
	@JsonView(VistaPerfil.class) private String usuario;
	@JsonView(VistaPerfil.class) private int numeroEmpleado;
	private String contrasena;

	public Maestro() {
	}

	public Maestro(Estatus estatus, String nombre, String usuario, int numeroEmpleado) {
		this.estatus = estatus;
		this.nombre = nombre;
		this.usuario = usuario;
		this.numeroEmpleado = numeroEmpleado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMaestro", unique = true, nullable = false)
	public Integer getIdMaestro() {
		return this.idMaestro;
	}

	public void setIdMaestro(Integer idMaestro) {
		this.idMaestro = idMaestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstatus", nullable = false)
	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "numeroEmpleado", nullable = false)
	public int getNumeroEmpleado() {
		return this.numeroEmpleado;
	}

	public void setNumeroEmpleado(int numeroEmpleado) {
		this.numeroEmpleado = numeroEmpleado;
	}
	
	@Column(name = "contrasena", nullable = false, length = 125)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

}
